# Generated by Django 5.0.4 on 2024-06-25 22:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_empleado_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='img'),
        ),
    ]
