# Generated by Django 5.0.4 on 2024-06-28 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_producto_compra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compra',
        ),
    ]
